Initial packagecloud support

diff --git a/ubuntu-defaults-image b/ubuntu-defaults-image
--- a/ubuntu-defaults-image
+++ b/ubuntu-defaults-image
@@ -27,6 +27,7 @@ COMPONENTS=
 MIRROR=
 SECURITY_MIRROR=
 PPAS=
+PCLOUDS=
 FLAVOR=ubuntu
 SUITE=$(lsb_release -sc)
 KEEP_APT_OPT=
@@ -53,8 +54,9 @@ Options:
   --security-mirror       : Ubuntu security mirror to be used during build
                             [default: http://security.ubuntu.com/ubuntu/]
   --ppa USER/PPANAME      : Enable additional PPA [default: none]
+  --pcloud USER/NAME      : Enable packagecloud repo [default: none]
   --keep-apt              : Do not remove apt indexes from live system
-  --keep-apt-components COMPONENTS : 
+  --keep-apt-components COMPONENTS :
                             Do not remove apt indexes for selected components from live
                             system [default: none]
 
@@ -79,6 +81,19 @@ add_ppas () {
         # add ppa apt source
         local DEB_PPA="deb http://ppa.launchpad.net/$ppa/ubuntu $SUITE main"
         echo "$DEB_PPA" >> config/archives/ubuntu-defaults.list
+    done
+}
+
+# add $PCLOUDS
+add_pclouds () {
+    for pcloud in $PCLOUDS; do
+
+        # fetch GPG key
+        curl -L https://packagecloud.io/${PCLOUD%/*}/${PCLOUD##*/}/gpgkey | apt-key --keyring config/archives/ubuntu-defaults.key add
+
+        # add ppa apt source
+				local PCLOUD_APT="deb https://packagecloud.io/${PCLOUD%/*}/${PCLOUD##*/}/ubuntu $SUITE main"
+        echo "$PCLOUD_APT" >> config/archives/ubuntu-defaults.list
     done
 }
 
@@ -127,6 +142,14 @@ while :; do
 		exit 1
 	    fi
 	    PPAS="$PPAS $2"
+	    shift 2
+	    ;;
+	--pcloud)
+	    if ! expr match "$2" '^[.[:alnum:]-]\+/[[:alnum:]-]\+$' >/dev/null; then
+		echo "Invalid packagecloud specification, must be username/reponame" >&2
+		exit 1
+	    fi
+	    PCLOUDS="$PCLOUDS $2"
 	    shift 2
 	    ;;
         --keep-apt)
